package com.nomad

import android.Manifest
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.activity.viewModels
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.core.content.ContextCompat
import com.nomad.ui.ChatScreen
import com.nomad.ui.theme.NomadTheme
import com.nomad.viewmodel.ChatViewModel
import kotlin.system.exitProcess

class MainActivity : ComponentActivity() {

    private val viewModel: ChatViewModel by viewModels()

    private val requestPermissionLauncher = registerForActivityResult(
        ActivityResultContracts.RequestMultiplePermissions()
    ) { permissions ->
        val anyGranted = permissions.isEmpty() || permissions.any { it.value }
        viewModel.onPermissionResult(anyGranted)
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        
        // Listen for permission requests from ViewModel
        lifecycle.addObserver(object : androidx.lifecycle.DefaultLifecycleObserver {
            override fun onResume(owner: androidx.lifecycle.LifecycleOwner) {
            }
        })

        setContent {
            NomadTheme {
                val state by viewModel.chatState.collectAsState()

                if (!state.hasAcceptedTerms) {
                    LegalDisclaimerDialog(
                        onAccept = { viewModel.acceptTerms() },
                        onDecline = { exitProcess(0) }
                    )
                }
                
                LaunchedEffect(state.showPermissionRationale) {
                    if (state.showPermissionRationale) {
                        checkPermissions()
                    }
                }

                NomadApp(viewModel)
            }
        }
    }

    private fun checkPermissions() {
        val permissions = mutableListOf<String>()
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            permissions.add(Manifest.permission.READ_MEDIA_IMAGES)
            permissions.add(Manifest.permission.READ_MEDIA_VIDEO)
            permissions.add(Manifest.permission.READ_MEDIA_AUDIO)
        } else {
            permissions.add(Manifest.permission.READ_EXTERNAL_STORAGE)
        }

        val toRequest = permissions.filter {
            ContextCompat.checkSelfPermission(this, it) != PackageManager.PERMISSION_GRANTED
        }

        if (toRequest.isNotEmpty()) {
            requestPermissionLauncher.launch(toRequest.toTypedArray())
        } else {
            viewModel.onPermissionResult(true)
        }
    }
}

@Composable
fun LegalDisclaimerDialog(onAccept: () -> Unit, onDecline: () -> Unit) {
    var isChecked by remember { mutableStateOf(false) }

    AlertDialog(
        onDismissRequest = { /* Prevent dismissal */ },
        containerColor = androidx.compose.ui.graphics.Color(0xFF0A0A0A),
        titleContentColor = androidx.compose.ui.graphics.Color.White,
        textContentColor = androidx.compose.ui.graphics.Color.White,
        title = { Text("⚖️ Terms & Disclaimer", fontWeight = FontWeight.Black) },
        text = {
            Column {
                Text(
                    "Welcome to Nomad. Please acknowledge the following to continue:\n\n" +
                    "• AI Content: Nomad is a local interface. All responses are generated by third-party models (Llama, Gemma, etc.). The developer is NOT responsible for AI-generated output.\n\n" +
                    "• Licenses: By using this app, you agree to comply with the community licenses of the models you download (Meta, Google, etc.).\n\n" +
                    "• Privacy: Nomad operates 100% offline. Local Insight and File Analysis data is NEVER uploaded.\n\n" +
                    "• ML Kit: On-device OCR uses Google Play Services APIs.\n\n" +
                    "• Not Advice: AI responses are not professional advice.",
                    style = MaterialTheme.typography.bodySmall
                )
                Spacer(Modifier.height(16.dp))
                Row(verticalAlignment = Alignment.CenterVertically) {
                    Checkbox(
                        checked = isChecked, 
                        onCheckedChange = { isChecked = it },
                        colors = CheckboxDefaults.colors(
                            checkedColor = androidx.compose.ui.graphics.Color.White,
                            uncheckedColor = androidx.compose.ui.graphics.Color.Gray,
                            checkmarkColor = androidx.compose.ui.graphics.Color.Black
                        )
                    )
                    Text("I have read and agree to these terms", style = MaterialTheme.typography.labelMedium)
                }
            }
        },
        confirmButton = {
            Button(
                enabled = isChecked,
                onClick = onAccept,
                colors = ButtonDefaults.buttonColors(
                    containerColor = androidx.compose.ui.graphics.Color.White,
                    contentColor = androidx.compose.ui.graphics.Color.Black
                ),
                shape = androidx.compose.foundation.shape.RoundedCornerShape(8.dp)
            ) {
                Text("ACCEPT & START", fontWeight = FontWeight.Bold)
            }
        },
        dismissButton = {
            TextButton(onClick = onDecline) {
                Text("DECLINE", color = androidx.compose.ui.graphics.Color.Gray)
            }
        }
    )
}

@Composable
fun NomadApp(viewModel: ChatViewModel) {
    ChatScreen(viewModel)
}
